project:
  type: website
  output-dir: docs/

website:
  title: "BILIS"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: primary
    search: true
    tools:
      - icon: github
        href: https://github.com/rfsaldanha/bilis_project
    left:
      - href: index.qmd
        text: Home
      - workflow.qmd
      - technology.qmd
      - indicators.qmd

format:
  html:
    theme: journal
    toc: true